version: '3.8'

services:
  app:
    container_name: currency_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT:-8000}:8000'
    command: ["gunicorn", "-b", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker", "currency_app.app:app"]

