version: '3.4'

services:
  a:
    container_name: currency_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:8000"
    env_file:
      - '.env'
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "-k", "uvicorn.workers.UvicornWorker", "currency_app.app:app"]
