version: '3.8'

services:
  app:
    container_name: currency_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - path: .env
        required: false
    ports:
      - '${PORT:-8000}:${PORT:-8000}'

